services:
  aircraft-database:
    build:
      target: development
    image: aircraft-database-development
    container_name: aircraft-database-development
    ports:
      - "9232:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    depends_on: 
      - aircraft-redis
    environment:
      REDIS_HOST: aircraft-redis

  aircraft-redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - "6381:6379"

volumes:
  redis_data:
