{{- include "helm-library.secret" (list . "aircraft-database.secret") -}}
{{- define "aircraft-database.secret" -}}
stringData:
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
{{- end -}}
