environment: production
name: aircraft-database
image: aircraft-database

container:
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 1000Mi
  limitCpu: 500m
  redisHost: services.lynxmagnus.com

deployment: {}

secret:
  secretsPath: /aircraft

cronJob:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  restartPolicy: Never
