environment: development
name: aircraft-database
image: aircraft-database

container:
  imagePullPolicy: Always
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 5Gi
  limitCpu: 1G
  redisHost:
  redisPassword:

deployment:
  restartPolicy: Always
  replicas: 1
  minReadySeconds: 0

secret:
  type: Opaque

cronJob:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  restartPolicy: Never
